backend/contacthub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls')),
    path('home/', include('home.urls')),
    path('tracker/', include('tracker.urls')),
    path('accounts/', include('allauth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

backend/home/urls.py
from django.urls import path
from . import views
from . import api


app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('publish-article/<int:pk>/', views.publish_article, name='publish-article'),
    path('api/', api.index),
    path('api-sample/', api.SampleView.as_view())
]

backend/home/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()
    published = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.title

backend/home/views.py
from django.shortcuts import render
from django.http.request import HttpRequest
from django.template.response import TemplateResponse
from django.http.response import HttpResponse, JsonResponse
from django.views.decorators.http import require_http_methods
from django.shortcuts import get_object_or_404



from .models import Article



def index(request: HttpRequest) -> HttpResponse:
    context = {'articles': Article.objects.all()}
    return render(request, 'index.html', context)



@require_http_methods(['POST'])
def publish_article(request: HttpRequest, pk: int) -> JsonResponse:
    article = get_object_or_404(Article, pk=pk)
    article.published = True
    article.save()
    return render(request, 'partials/_article_row.html', {'article': article})

backend/templates/html/home/partials/_article_row.html
<tr>
    <td>{{ article.title }}</td>
    <td>{{ article.description }}</td>
    <td>{{ article.published }}</td>

    <td>
        {% if not article.published %}
        <button class="btn btn-xs btn-accent" id="publish-button" data-article-id="{{ article.pk }}">Publish [AJAX]</button>
        <button 
            class="btn btn-xs btn-accent"
            id="htmx-button"
            hx-post="{% url 'home:publish-article' article.pk %}"
            hx-target="closest tr"
            hx-swap="outerHTML">
        Publish [HTMX]
        </button>
        {% endif %}
    </td>
</tr>